INSERT INTO Product (name, price, createdAt, updatedAt) VALUES
('Teclado Mecánico RGB', 120.0, datetime('now'), datetime('now')),
('Mouse Gamer Inalámbrico', 85.0, datetime('now'), datetime('now')),
('Silla Ergonómica de Oficina', 250.0, datetime('now'), datetime('now')),
('Cafetera Italiana', 40.0, datetime('now'), datetime('now')),
('Zapatillas Running Pro', 180.0, datetime('now'), datetime('now')),
('Audífonos Bluetooth', 95.0, datetime('now'), datetime('now')),
('Smartwatch Deportivo', 220.0, datetime('now'), datetime('now')),
('Freidora de Aire', 150.0, datetime('now'), datetime('now')),
('Cámara Fotográfica Compacta', 340.0, datetime('now'), datetime('now')),
('Ventilador de Torre', 75.0, datetime('now'), datetime('now')),
('Plancha de Ropa a Vapor', 55.0, datetime('now'), datetime('now')),
('Licuadora Industrial', 130.0, datetime('now'), datetime('now')),
('Monitor 27" 144Hz', 420.0, datetime('now'), datetime('now')),
('Almohada Memory Foam', 45.0, datetime('now'), datetime('now')),
('Aspiradora Robot', 390.0, datetime('now'), datetime('now')),
('Set de Ollas Antiadherentes', 110.0, datetime('now'), datetime('now')),
('Juego de Herramientas 100 piezas', 90.0, datetime('now'), datetime('now')),
('Mouse Pad XL', 25.0, datetime('now'), datetime('now')),
('Smart TV 55"', 900.0, datetime('now'), datetime('now')),
('Cepillo Alisador', 60.0, datetime('now'), datetime('now')),
('Perfume Floral 100ml', 75.0, datetime('now'), datetime('now')),
('Consola de Videojuegos', 650.0, datetime('now'), datetime('now')),
('Control Xbox Inalámbrico', 80.0, datetime('now'), datetime('now')),
('Bicicleta Urbana', 310.0, datetime('now'), datetime('now')),
('Patineta Eléctrica', 500.0, datetime('now'), datetime('now')),
('Set de Cubiertos Acero', 35.0, datetime('now'), datetime('now')),
('Mesa Plegable Portátil', 48.0, datetime('now'), datetime('now')),
('Carpa para Camping 4 Personas', 120.0, datetime('now'), datetime('now')),
('Linterna LED Recargable', 22.0, datetime('now'), datetime('now')),
('Botella Térmica 1L', 18.0, datetime('now'), datetime('now')),
('Cortadora de Cabello', 45.0, datetime('now'), datetime('now')),
('Drone Profesional', 780.0, datetime('now'), datetime('now')),
('Set de Pinturas Acrílicas', 28.0, datetime('now'), datetime('now')),
('Auriculares Studio', 190.0, datetime('now'), datetime('now')),
('Karaoke Inalámbrico', 140.0, datetime('now'), datetime('now')),
('Multiherramienta Suiza', 32.0, datetime('now'), datetime('now')),
('Kit de Pesas Ajustables', 260.0, datetime('now'), datetime('now')),
('Colchón Ortopédico Queen', 750.0, datetime('now'), datetime('now')),
('Cámara IP de Seguridad', 65.0, datetime('now'), datetime('now')),
('Router Wi-Fi 6', 98.0, datetime('now'), datetime('now')),
('Set de Destornilladores', 20.0, datetime('now'), datetime('now')),
('Termo Eléctrico', 130.0, datetime('now'), datetime('now')),
('Horno Eléctrico 45L', 210.0, datetime('now'), datetime('now')),
('Teclado Minimalista', 55.0, datetime('now'), datetime('now')),
('Gafas de Sol Polarizadas', 38.0, datetime('now'), datetime('now')),
('Parlante Bluetooth Portátil', 70.0, datetime('now'), datetime('now')),
('Juego de Sábanas Queen', 48.0, datetime('now'), datetime('now')),
('Microondas 30L', 260.0, datetime('now'), datetime('now')),
('Cámara Deportiva 4K', 220.0, datetime('now'), datetime('now')),
('Mochila Antirrobo', 55.0, datetime('now'), datetime('now')),
('Refrigeradora 300L', 1200.0, datetime('now'), datetime('now')),
('Lavadora 12kg', 950.0, datetime('now'), datetime('now')),
('Secadora de Ropa', 750.0, datetime('now'), datetime('now')),
('Escritorio Gamer LED', 230.0, datetime('now'), datetime('now')),
('Silla Gamer Premium', 350.0, datetime('now'), datetime('now')),
('Máquina de Coser', 330.0, datetime('now'), datetime('now')),
('Set de Tuppers Herméticos', 25.0, datetime('now'), datetime('now')),
('Aro de Luz Profesional', 85.0, datetime('now'), datetime('now')),
('Guantes de Gym', 18.0, datetime('now'), datetime('now')),
('Maleta de Viaje Grande', 140.0, datetime('now'), datetime('now')),
('Purificador de Aire', 300.0, datetime('now'), datetime('now')),
('Set de Jardinería Completo', 42.0, datetime('now'), datetime('now')),
('Cargador Rápido USB-C', 28.0, datetime('now'), datetime('now')),
('Disco Duro Externo 2TB', 110.0, datetime('now'), datetime('now')),
('Teclado Para Tablet', 34.0, datetime('now'), datetime('now')),
('Cámara Retro Instantánea', 160.0, datetime('now'), datetime('now')),
('Juguera Extractora', 170.0, datetime('now'), datetime('now')),
('Auto RC Profesional', 210.0, datetime('now'), datetime('now')),
('Kit de Maquillaje Pro', 85.0, datetime('now'), datetime('now')),
('Lámpara LED Escritorio', 22.0, datetime('now'), datetime('now'));
